name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with: 
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version
            

      - name: DockerHub login
        env:
          DOCKER_USERNAME: ${{  secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "INICIANDO LOGIN"
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          echo "FIN DEL LOGIN"
          echo "Nueva version $NEW_VERSION"
          

      # - name: Build the Docker image
      #   env:
      #     NEW_VERSION: ${{ steps.version.outputs.version }}
      #   run: |
      #     docker build -t jeada22/kittens:$NEW_VERSION .
      #     docker build -t jeada22/kittens:latest .
          
      # - name: Push the Docker image
      #   env:
      #     NEW_VERSION: ${{ steps.version.outputs.version }}
      #   run: |
      #     docker push jeada22/kittens:$NEW_VERSION
      #     docker push jeada22/kittens:latest

      - name: Login to Digital Ocean Registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin registry.digitalocean.com

      - name: build and push the Docker image to Digital Ocean
        run: |
          docker build -t registry.digitalocean.com/kittens/jeada22/kittens --push .